
Dhrystone Benchmark, Version C, Version 2.2
Program compiled without 'register' attribute

Trying 500 runs through Dhrystone:
Final values of the variables used in the benchmark:

Int_Glob:            5
        should be:   5
Bool_Glob:           1
        should be:   1
Ch_1_Glob:           A
        should be:   A
Ch_2_Glob:           B
        should be:   B
Arr_1_Glob[8]:       7
        should be:   7
Arr_2_Glob[8][7]:    510
        should be:   510
Ptr_Glob->
  Ptr_Comp:          78696
        should be:   (implementation-dependent)
  Discr:             0
        should be:   0
  Enum_Comp:         2
        should be:   2
  Int_Comp:          17
        should be:   17
  Str_Comp:          DHRYSTONE PROGRAM, SOME STRING
        should be:   DHRYSTONE PROGRAM, SOME STRING
Next_Ptr_Glob->
  Ptr_Comp:          78696
        should be:   (implementation-dependent), same as above
  Discr:             0
        should be:   0
  Enum_Comp:         1
        should be:   1
  Int_Comp:          18
        should be:   18
  Str_Comp:          DHRYSTONE PROGRAM, SOME STRING
        should be:   DHRYSTONE PROGRAM, SOME STRING
Int_1_Loc:           5
        should be:   5
Int_2_Loc:           13
        should be:   13
Int_3_Loc:           7
        should be:   7
Enum_Loc:            1
        should be:   1
Str_1_Loc:           DHRYSTONE PROGRAM, 1'ST STRING
        should be:   DHRYSTONE PROGRAM, 1'ST STRING
Str_2_Loc:           DHRYSTONE PROGRAM, 2'ND STRING
        should be:   DHRYSTONE PROGRAM, 2'ND STRING
        
tb_RISCV32I.vhdl:196:25:@107756fs:(report note): Se genero Interrupcion
tb_RISCV32I.vhdl:193:25:@108116fs:(report note): Se detecto y manejo Interrupcion
tb_RISCV32I.vhdl:173:25:@249276fs:(report note): Exception Cause: 4
tb_RISCV32I.vhdl:173:25:@409636fs:(report note): Exception Cause: 4
tb_RISCV32I.vhdl:196:25:@428900fs:(report note): Se genero Interrupcion
tb_RISCV32I.vhdl:193:25:@429260fs:(report note): Se detecto y manejo Interrupcion
tb_RISCV32I.vhdl:173:25:@570588fs:(report note): Exception Cause: 6
tb_RISCV32I.vhdl:173:25:@730980fs:(report note): Exception Cause: 6
tb_RISCV32I.vhdl:173:25:@891956fs:(report note): Exception Cause: 3
tb_RISCV32I.vhdl:173:25:@1052380fs:(report note): Exception Cause: 2
tb_RISCV32I.vhdl:196:25:@1054620fs:(report note): Se genero Interrupcion
tb_RISCV32I.vhdl:173:25:@1212948fs:(report note): Exception Cause: 0
tb_RISCV32I.vhdl:173:25:@1373972fs:(report note): Exception Cause: 0
tb_RISCV32I.vhdl:173:25:@1534508fs:(report note): Exception Cause: 0

ciclos 283341

bash compile.sh benchmarks/exceptions/dhrystone_main '-O3 -D EXPTEST' 'benchmarks/exceptions/dhrystone.c'
